### PR TITLE
Adding support of vlan facts to get_facts() and vlan mode to get_vlan_config_commands()

### PR DESCRIPTION
**Pull request by jonasstenling**
**_New lib function get_vlan_info()**_
Return list of dicts with detailed information regarding VLANs.

**_Adding gathering of vlan facts to get_facts() through get_vlan_info()**_
Making it possible to check if a device already has a vlan configured, like so:

```
name: add vlan
  hosts: test01

  tasks:

    - name: getting facts...
      nxos_get_facts:
          username={{ username }}
          password={{ password }}
          detail=true
          host={{ inventory_hostname }}

    - name: Checking if vlan already exists in switch...
      fail: 'msg="ERROR: VLAN exists in switch"'
      when: "{{ item.vlan_id }} == {{ vlan_id }}"
      with_items: vlan_list
```

**_Adding support of vlan mode (ce or fabricpath) to get_vlan_config_commands().**_
Required to support mode=(ce|fabricpath) in nxos_vlan Ansible module. Update to Ansible module to be submitted in separate pull request.

### CODE REVIEW

**Comment by jedelman8** [comment]
Don't mean to be a pain, but you can still be calling `get_vlan` in your loop.  The only difference is you added a new key (`ifidx`) to the vlan dict.  And the keys should really be consistent meaning facts shouldn't return a get that `get_vlan` doesn't.  If you want, just add your new key to the dict being returned by `get_vlan`.  Please also make `ifidx` something that is better understood, or human readable :)

**Comment by jonasstenling** [comment]
Iterating with `get_vlan()` would trigger n \* vlans nxapi calls to the switch. With hundreds of vlans that would be both slow and cpu intensive. The new function solves this in a more efficient way.

I agree regarding the naming for ifidx and the consistency with `get_vlan()`. I can change the name and add it to `get_vlan()` as well. Any suggestion on the naming? From "show vlan id" the column is named "Ports", but maybe "interfaces" is better?

**Comment by jedelman8** [comment]
That was a test :).  If you did make the change, I was going to have you undo it!  Sorry about that...was getting ready for vacation on my last comment!  "interfaces" works, but if it's multiple, you may want to loop through and just get the interface names.  Not sure what data is returned (have not tested), but let's keep it clean and accessible, so it _seems_ to make sense to have the value returned be a list of interfaces.

**Comment by jonasstenling** [comment]
It seems like ifidx will return ranges of interfaces, like `"ifidx": "Ethernet1/1-2,Ethernet1/5-9,Ethernet1/11-28,Ethernet2/1-5,Ethernet2/8-16"`. My suggestion would then be to unpack all the ranges and return a list like `interfaces = ['Ethernet1/1', 'Ethernet1/2', 'Ethernet1/5' ... ]`. I think I can use your `vlan_range_to_list()` function to do the unpacking, if it's OK with you. Otherwise I'll create a separate support function to do it.

**Comment by jedelman8** [comment]
Of course, if it does what you need it to do! Please use it!

**Comment by jonasstenling** [comment]
Ok, this commit adds the functionality to get_facts().

Regarding your comment on adding the `interfaces` key to `get_vlan()`. I looked at the `nxos_vlan` Ansible module that is using `get_vlan()` and the way its written currently the `interfaces` key would be added to the existing commands that are then pushed to the device. I don't know if that's what we want?

**Comment by jedelman8** [comment]
Thank you!  BTW, you need to re-open your PR for the Ansible module...sorry about that.

**Pull request merged**
