### PR TITLE
Catch errors when a single entity is returned

### PR DESCRIPTION
**Pull request by ahill00**
When the API returns a single entity, AttributeError gets thrown on .get()s,
we should catch that error.

### CODE REVIEW

**Comment by ahill00** [comment]
This was being thrown on 3K which had a single module:

```
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424987477.27-91879394374599/nxos_get_facts", line 1719, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424987477.27-91879394374599/nxos_get_facts", line 117, in main
    facts = nxapi_lib.get_facts(device)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/utils/nxapi_lib.py", line 2270, in get_facts
    temp['ports'] = str(each.get('ports', None))
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jedelman8** [comment]
Ah, I'm aware of this. Missed this one though :).  On the road now- guess this was for a single power supply or fan? 

Will check this out and merge later or first thing tomorrow. 

Thanks!
Jason

**Comment by heathdbrown** [comment]
@jedelman8 we found this when using Nexus 3ks:

```
{
  "ins_api": {
    "type": "cli_show",
    "version": "1.0",
    "sid": "eoc",
    "outputs": {
      "output": {
        "input": "show module",
        "msg": "Success",
        "code": "200",
        "body": {
          "TABLE_modinfo": {
            "ROW_modinfo": {
              "modinf": 1,
              "ports": 52,
              "modtype": "48x10GE + 4x40G Supervisor            ",
              "model": "N3K-C3064PQ-10GX-S",
              "status": "active *    "
            }
          },
          "TABLE_modmacinfo": {
            "ROW_modmacinfo": {
              "modmac": 1,
              "mac": "24e9.b39e.04e8 to 24e9.b39e.0527",
              "serialnum": "removed"
            }
          },
          "TABLE_modwwninfo": {
            "ROW_modwwninfo": {
              "modwwn": 1,
              "sw": "6.0(2)U4(3) ",
              "hw": "1.5  ",
              "wwn": "--"
            }
          }
        }
      }
    }
  }
}
```

**Comment by ahill00** [comment]
The failure was only seen on modules but I went ahead and cleaned up the similar cases.

**Comment by jedelman8** [comment]
Did you test this?  I could swear we need parantheses around multiple exceptions in Python.  I'll add them in to be safe.

**Pull request merged**
